### ISSUE TITLE
Host name issues in guestbook-app/frontend-ingress.yaml

### ISSUE THREAD

**Issue by MiddelkoopT** [wangso/mizzou_nautilus_k8s_lab#2]
The `host:` declaration in the docs does not match and may not support multiple students.

From the doc's.
```
9.5.1 Open “frontend-ingress.yaml” and examine the code in the file:
apiVersion: extensions/v1beta1 kind: Ingress
metadata:
annotations:
kubernetes.io/ingress.class: traefik traefik.ingress.kubernetes.io/router.tls: ””
name: test-ingress spec:
rules:
- host: test-service.nautilus.optiputer.net
http:
paths:
- backend:
serviceName: test-svc
servicePort: 80 path: /
```

uses `test-service.nautilus.optiputer.net` but the rest of the instructions use `guestbook.nautilus.optiputer.net`.  This will also cause issues if more than one student creates the ingress at the same time.

**Comment by wangso** [comment]
Missed adding a warning in this section. Updated...
